### PR TITLE
Add back onChange for Autocomplete to enable freeSolo functionality

### LINKED ISSUE #167: [feat] Autocomplete doesn't support the `freeSolo` option
**Describe the bug**
I can't seem to get the `Autocomplete` component to work correctly with the `freeSolo` option to allow adding new items not already in the list. When typing in an item that doesn't exit and adding it, the item doesn't get added.

**To Reproduce**
1. Add the `freeSolo={true}` prop to the `Autocomplete` component.
2. Type in a new option that doesn't exist in the pre-defined options.
3. Add the option.
4. See that no option is added. If you log the form values you can see that the value is correctly set, but not displayed on the component.

**Expected behavior**
The component should correctly reflect the value of the form.

**Additional context**
I believe that the problem arises here: https://github.com/lookfirst/mui-rff/blob/f734b65123de9fba29223ed1db43f36ee7795015/src/Autocomplete.tsx#L80-L94

The code iterates over `options` and checks the against the `value`, but it should probably be inverted for cases where items are not in `options`. This filtering specifically happens in these lines: https://github.com/lookfirst/mui-rff/blob/f734b65123de9fba29223ed1db43f36ee7795015/src/Autocomplete.tsx#L85-L87

### PR DESCRIPTION
**Pull request by radicand**
This pull request allows a user to pass the onChange callback to the MUI-RFF Autocomplete component, so they can deal with the case of new options being added in their code, according to how they've implemented their options array.

The re-addition of onChange is handled as an optional callback that is called in addition to the "under the hood" onChange handling if present. It does not change how the component currently works, it only surfaces the event to the front end.

Examples file updated with functional examples based on https://material-ui.com/components/autocomplete/#creatable

Fixes #167

### CODE REVIEW

**Comment by lookfirst** [comment]
Sweet, this probably needs some more tests too. =)

**Comment by radicand** [comment]
> Sweet, this probably needs some more tests too. =)

Couldn't hurt - I have to admit though that frontend testing is not my forte; not sure where to begin with a test suite to validate this.

**Comment by radicand** [comment]
@lookfirst - added a test to validate the behavior, also improved some typing for the element while i was at it.

**Comment by lookfirst** [comment]
@radicand Thank you! I'll carve out some time this weekend for mui. =)

**Comment by DASPRiD** [comment]
I hope you can get this merged soon – I'm also blocked by this right now :)

**Comment by lookfirst** [comment]
@radicand Would you mind updating this PR for the latest version of MaterialUI? I've been struggling on the types for a bit now and I could use some help.

**Comment by lookfirst** [comment]
Just `yarn ui` in the top level and it'll update everything.

**Comment by radicand** [comment]
Sure, I'll try to take a look in the next few days

**Comment by lookfirst** [comment]
Thank you! I'm back now working on things. =)

**Comment by radicand** [comment]
I updated for to latest MUI and types check out now - you may need to update the snapshots for tests on your end to accomodate MUI rendering changes. Can you take a look at that? A lot of the snapshot tests are failing now, but I suspect they are not actual errors but just snapshots that need to be updated.

**Comment by lookfirst** [comment]
@radicand Thanks for your update! 

Ok, I've fixed a whole bunch of stuff such that the only failing rests are around Autocomplete.

I've pushed my changes to this branch:

https://github.com/lookfirst/mui-rff/tree/pr228

I'm not really sure how to fix things. Autocomplete is totally broken in the example app.

**Comment by lookfirst** [comment]
@radicand Now I get to ping you. =)

**Comment by radicand** [comment]
Thanks for the ping -- buried with work recently. I should have some time over the weekend though - I'll aim to resolve before Monday.

**Comment by lookfirst** [comment]
@radicand No worries! I totally get it... I also apologize for creating a new branch... not really sure if I can actually push to your branch or what... heh. =) Anyway, thanks for all the help, your last set of changes were really good.

**Comment by radicand** [comment]
Working on this - something strange happened on the MUI side with recent versions that I'm attempting to debug. You're right that the component is totally broken right now.

**Comment by lookfirst** [comment]
Thanks @radicand Yea... this is why I love having a bunch of tests... I don't trust MUI to not break things. =(

**Comment by radicand** [comment]
@lookfirst good to go. Passing inputProps to the TextField element does not appear to work nicely anymore. It doesn't appear it's required either -- all tests pass and the example functions normally.

**Comment by lookfirst** [comment]
Wee... I just merged these changes... tests are still wonky, but I'll figure it out.

**Comment by lookfirst** [comment]
I released this as part of v2.2.0, so I'm going to close. Thanks for the hard work on this and apologies for the delays!

**Pull request closed without merging**
