### PR TITLE
(fix) datepicker does not turn red if invalid value #604

### PR DESCRIPTION
**Pull request by benoit-nadaud**
- datepicker does not turn red if invalid value
 - tried to complete DatePicker test with a test with empty value submission

### CODE REVIEW

**Comment by benoit-nadaud** [comment]
Let me know if i did not followed the contribution process properly, apparenty i did not managed to link my PR to the issue 604

**Comment by lookfirst** [comment]
@benoit-nadaud Thanks for the contribution. It looks great. Just make sure to sign that CLA.

To link issues, you put a `#` in front of them.

**Comment by benoit-nadaud** [comment]
Ok, i signed it

**Comment by lookfirst** [comment]
@benoit-nadaud Thanks! Apologies for the delay, github was having some issues and I couldn't merge it. I'll do a release now too.

**Comment by lookfirst** [comment]
@benoit-nadaud v3.1.1 is released

**Comment by benoit-nadaud** [comment]
U mean 5.1.1 i suppose. Already installed it on my project

Le sam. 19 mars 2022 à 22:24, Public Profile ***@***.***> a
écrit :

**Comment by lookfirst** [comment]
@benoit-nadaud apologies, yes... 5.1.1.

**Pull request merged**
