### PR TITLE
override typing of yup

### PR DESCRIPTION
**Pull request by japrescott**
followup to https://github.com/lookfirst/mui-rff/pull/198

### CODE REVIEW

**Comment by lookfirst** [comment]
Thanks! I fixed this another way... by pushing the responsibility to do typing up into the translator function. =)

The bigger issue is that YupValidationError.message has the wrong type and fixing that is a whole lot more of a pain in the ass than just letting implementors do what they want. =)

This also gives more flexibility... working with the whole YupValdationError is more fun.

**Comment by lookfirst** [comment]
@japrescott By the way, I apologize for 'breaking' your backwards compatibility for your app... but given that mui-rff hadn't been released yet and you're probably the only person using it, I figured it would be ok... =) the fix is also pretty simple though...

**Comment by japrescott** [comment]
thanks for your feedback. I will look into in detail on monday, sounds very exciting. looks great! I didnt want to fuckup everything for other devs.. so maybe a minor release bump would help others that rely on this?! Anyway, thanks for the constructive talks

**Comment by lookfirst** [comment]
all good, you're the only one who i would have broken. code is released already. =)

**Pull request closed without merging**
