### PR TITLE
fixed autocomplete active state

### PR DESCRIPTION
**Pull request by ErikParso**
Autocomplete field active meta state was not set due to absence of onFocus and and onBlur events.

### CODE REVIEW

**Comment by lookfirst** [comment]
Thanks for this. Going to need some unit tests though (and have them pass).

**Comment by ErikParso** [comment]
Well this one test didn't pass even before my changes. I am not doing any additional tests or fixing this one

**Comment by ErikParso** [comment]
> Thanks for this. Going to need some unit tests though (and have them pass).

done

**Comment by lookfirst** [comment]
excellent work! 6.2.3 was just published. thanks!

**Pull request merged**
