### PR TITLE
fix autocomplete state change

### PR DESCRIPTION
**Pull request by igakim**
#308 

May be this can solve the bug? =) Not sure if i did it right

### CODE REVIEW

**Comment by lookfirst** [comment]
Not sure either... do your tests pass?

but the [type definition](https://github.com/lookfirst/mui-rff/blob/90486cf6b6bc376cd7c9398f036692a534331f03/src/Autocomplete.tsx#L105) is 'undefined'... not 'null'.... so we either need to widen it or change it.

**Comment by igakim** [comment]
Tests passed, and i currently use this solution and don't get warnings. 

Also, i tried to pass to MuiAutocomplete `value` props conditional value

```js
value={defaultValue || null}
```
and it also works well. But I'm not sure if this solution follows the general style of lib.

i'm not strong in TS, i use JS. Sorry for the useless bother if my suggestions are not applicable

**Comment by lookfirst** [comment]
Tests may pass, but that's a bad thing. It likely means that there isn't coverage for what already is failing. So what I'd want to see in this PR is a test for the failing case and then the fix. Yes, we also need to figure out the types as well. Highly suggest that you strengthen your TS as JS is a dead horse long term. =)

**Comment by bmleight** [comment]
I've been looking into this issue as well, and the following changes have been working well for me.  The changes are to set defaultValue when it's defined (so it can never be `undefined`), and remove initializing it to an empty array when looping through all options in multiple is true:

```
let defaultValue: Value<T, Multiple, DisableClearable, FreeSolo> | undefined = multiple ? [] as any : null;

if (!getOptionValue) {
    defaultValue = value as Value<T, Multiple, DisableClearable, FreeSolo> | undefined;
} else if (value) {
    options.forEach((option) => {
        const optionValue = getOptionValue(option);
        if (multiple) {
            (value as any).forEach((v: any) => {
                if (v === optionValue) {
                    (defaultValue as any).push(option);
                }
            });
        } else {
            if (value === optionValue) {
                defaultValue = option as any;
            }
        }
    });
}
```

My issue surfaced around using the multiple prop.  I fetch the list of options from an API, so on the initial render, there are no options, resulting in `undefined` getting passed into material's autocomplete component.  This causes the component to switch from uncontrolled to controlled when the list of options is returned, and in turn broke clearing the autocomplete's value when resetting the form.  I don't think we ever want to pass undefined into material's autocomplete as the value.  That is what triggers the component to function in uncontrolled mode.

**Comment by lookfirst** [comment]
@bmleight Your types are all messed up though. =) Likely need to get rid of undefined and just use null.

**Comment by bmleight** [comment]
@lookfirst agreed, I didn't make any changes to types, it still needs cleanup like that, and as you mentioned more tests would be great as well.

**Comment by bmleight** [comment]
updated my example, removing the `| undefined`, but there are still a few `any`'s floating around.

**Comment by deepak-evry** [comment]
Hi why still not merged this PR

**Comment by deepak-evry** [comment]
Any workaround for this?

**Comment by lookfirst** [comment]
I'm going to close this, I'm guessing it is no longer an issue. If you feel it is, feel free to comment here and we can continue to discuss.

**Pull request closed without merging**
