### PR TITLE
Adds/fixes onChange support for all fields

### PR DESCRIPTION
**Pull request by richnicholls-flex**
Adds the ability to pass `onChange={(value, previousValue) => { console.log("field value changed", { value, previousValue }) }}` to all fields. `onChange` is supported by a lot of the fields at the moment (because of extending MUI field prop interfaces), but passing anything in breaks the inputs as it stops RFF from passing in its own function to control the form state. This fixes those problems.

I've also added it into the examples document, and ran eslint. However, I haven't added any tests so I imagine it *may* block approval, even though it fixes the existing onChange RFF override bug.

### CODE REVIEW

**Comment by lookfirst** [comment]
Thank you for this contribution. It is a lot of work, but I wish we had discussed it in an issue before you made all these changes. I have to admit, I'm not sure about this contribution, but I'm open to discussion for sure. 

Here is my reasoning:

1. Yes, definitely needs tests. That should always be the first thing you start with, especially with changes like this.
1. Responding to change events is kind of different when it comes to RFF. You should be able to `useEffect` watch the output of either the `FormState` or the submission data. This leaves the control within RFF itself, which I like. This PR effectively side steps all of that for a lot more complexity.
1. You added `onChange` to everything in the example. That is definitely not what I would want to require or even encourage people to do.
1. The next step would be to also consider all the other events, for example, what about blur and focus?
1. There is a number of good little separate changes that you made, like simplifying the logic for single and using 'uknown'. I'd submit anything not related to the onChange as a separate PR.

Anyway, let me know what you are thinking.

**Comment by richnicholls-flex** [comment]
The example file I edited used onChange for all of the inputs just as a demo, much like helperText was used for a lot of the controls. It was definitely never intended to work as a method of storing changes separately from how RFF uses state or anything like that, just to show off that it does work for all of the controls with a common API (calling the callback with value and previousValue as args). In my use-case I had a couple of inputs that I need to watch for changes. When I change a date I needed to do something else. For this to work I wanted to listen for changes to a field, but combining useEffect with FormState is a good idea! (Damn, wish I'd thought of that!). My implementation was a bit non-DRY because I didn't see a place for utility functions. I would have liked to have used a wrapper around the MUI component usage to solve this (and address onBlur and onFocus too).

The current released implementation does however have an issue where passing in the `onChange` prop causes the input to break and not update, so this was halfway between a fix and a feature. Keeping the omits of 'onChange' on the prop inheritance would probably stop people making that mistake in light of your useEffect approach.

As for the tests, I wasn't sure you'd be happy with the API (maybe wanting events to be passed around too) or if you had other issues (which you outlined above :)).

Your useEffect + FormState approach solves my issue completely, so I will use that (and only suffers with having to store the previousValue in state that my PR would solve - but then mine adds the complexity and, honestly, isn't as smell-free as your useEffect idea). Ignore this for now then. If there's anything you can rip out of it feel free :) - or send me a couple of issues that relate to what I've done and I'll try and issue a couple of PRs. I do really like this library and I hope you keep up the good work!

**Comment by lookfirst** [comment]
@richnicholls-flex Thanks for the response! Thanks for the compliments about the project. It has been a surprisingly large amount of work for something that is supposed to be so simple! =)

Agreed, overriding `on*` breaks things. I can remove that from the types to solidify that. You really shouldn't override it. =)

Glad that `useEffect` works for you. Let me know if you run into issues with it. I know that I fixed something with `Autocomplete` recently around that.

For the previous value state, you can likely contain that into a hook or state management system like [mobx-state-tree middleware](https://github.com/mobxjs/mobx-state-tree/tree/master/packages/mst-middlewares#undomanager). Again, separating the concerns.... your mui-rff forms shouldn't care about any state themselves... they just render the data given to them.

I'll leave this open for now and pull out the good bits that I like. =)

Stay safe. The world is a bit crazy right now.

**Comment by lookfirst** [comment]
Ok, I took your good bits and just did a release. Thanks so much!

**Pull request closed without merging**
