### PR TITLE
chore: upgrade to mui v6

### LINKED ISSUE #1169: Upgrade to MUI 6.x
Well, basically that.

### PR DESCRIPTION
**Pull request by lukas-cc**
Updated to MUI v6.

Closes #1169

### CODE REVIEW

**Comment by lukas-cc** [comment]
Let me know if there is something missing or not quite right. 
According to this [guide](https://mui.com/material-ui/migration/upgrade-to-v6/#breaking-changes-affecting-types) there are no breaking changes affecting mui-rff

**Comment by lookfirst** [comment]
@lukas-cc need to fix whatever the build issues are.

**Comment by lukas-cc** [comment]
> @lukas-cc need to fix whatever the build issues are.

It was the snapshots. Updated them now @lookfirst

**Comment by lookfirst** [comment]
https://mui.com/material-ui/migration/upgrade-to-v6/#ripple-effect

**Comment by lukas-cc** [comment]
I looked into the test code and in some places (e.g. Switches test code) `fireEvent` was already wrapped in a `act()`. But it seems that the ripple was still removed from the snapshot.

**Comment by lukas-cc** [comment]
If there is anything I should look into let me know and I'll try my best @lookfirst

**Review by jon-hotaisle — APPROVED** [review]
LGTM

**Comment by lookfirst** [comment]
@lukas-cc sorry, software seems to rot over time. parcel now segfaults. Not sure if it is related to this:

https://github.com/parcel-bundler/parcel/issues/9926#issuecomment-2369971853

**Comment by lukas-cc** [comment]
No worries - appreciate all the work you've put into this!

**Pull request merged**
