### PR TITLE
[Autocomplete] Initial values can't sets #107

### PR DESCRIPTION
**Pull request by popuguytheparrot**
add missing props

### CODE REVIEW

**Comment by lookfirst** [comment]
Thank you for the contribution, this is great. We need a test for it and the existing tests seem to be failing...

**Comment by lookfirst** [comment]
This has been fixed separately, it was a bit more involved than your PR. =(

**Comment by popuguytheparrot** [comment]
@lookfirst i checked pr. Your use defaultValue not correct. It props for uncontrolled input.
https://codesandbox.io/s/react-final-form-material-ui-example-gzx4p

**Comment by lookfirst** [comment]
Larry doesn't exist in the list of options. Also need `multiple=true` and to mark the initialValues value as an array. I've updated your example:

https://codesandbox.io/s/react-final-form-material-ui-example-03i8q

**Pull request closed without merging**
