### PR TITLE
adapt more input type for TextField

### PR DESCRIPTION
**Pull request by zhuangya**
input with `search` type does not hold a role of 'textbox', so the test
would fail for `search` type, so the `search` type is not included yet.

ref #116

### CODE REVIEW

**Comment by lookfirst** [comment]
1.8.1

**Comment by zhuangya** [comment]
thank you very much :)

**Comment by lookfirst** [comment]
@zhuangya , no... thank you! =) if you find anything else, let me know... your contribution was excellent!

**Comment by llermaly** [comment]
any chance to add type=color ? :(

**Comment by lookfirst** [comment]
> any chance to add type=color ?

yes, check the latest release! (5.1.1) =) (sorry for the delay).

**Pull request merged**
