### PR TITLE
fixed pickers warning

### PR DESCRIPTION
**Pull request by ErikParso**

### CODE REVIEW

**Comment by lookfirst** [comment]
Hi @ErikParso, thanks for the PR! Please remove the changes in the lock files. We don't use a package-lock (npm) and the other change shouldn't be necessary either.

**Comment by ErikParso** [comment]
Can do, but i had to uptade snapshots, they didnt match even before my changes

**Comment by lookfirst** [comment]
@ErikParso snapshots should not need updating before your changes. otherwise they wouldn't pass CI. =)

**Comment by ErikParso** [comment]
Sorry my bad you are right. Indeed the snapshots are definitely different. This fix has this interesting effect.

**Original state:**

When date form value is initially undefined, the field renders with label shrinked. Form my point of view and how the mui picker component behaves by default, this is incorrect. The label should be expanded and shrink only when field is focused or holds value.

**After this fix:**

When date form value is initially undefined, field renders with label expanded.

image

Thats why snapshots are different.

**Comment by lookfirst** [comment]
Sure, so we are still going to need the updated snaps since you're fixing the behavior that was recorded before. That's why the tests are failing now. =)

**Comment by ErikParso** [comment]
> Sure, so we are still going to need the updated snaps since you're fixing the behavior that was recorded before. That's why the tests are failing now. =)

I reverted the changes in snapshots

**Comment by ErikParso** [comment]
I updated the snapshots now its passing. So, if new behavior I described is acceptable we can finish this PR

**Comment by ErikParso** [comment]
Also now it should be compatible with moment.js not only date-fns,

**Comment by lookfirst** [comment]
Great work @ErikParso ! Thanks so much for your contribution. I really appreciate it!

**Pull request merged**
