### PR TITLE
Add variant prop for DatePicker, TimePicker and DateTimePicker

### PR DESCRIPTION
**Pull request by mxt305**
To fix issue #575
Unable to change `variant` props of DatePicker, TimePicker and DateTimePicker in 5.x

### CODE REVIEW

**Comment by lookfirst** [comment]
Ok, I looked into this. I'm not happy with this solution because it involves more than just the variant property. It would be the ability to pass in any property to the TextInput within the renderInput of the Date* component.

This is unfortunately a much larger change than just this PR, so I'm going to close it. If you'd like to work on this with me, I'm happy to help you think about things further.

**Comment by lookfirst** [comment]
As others have noted in the issue, the solution is: `<DatePicker  TextFieldProps={{ variant: 'standard' }} />`

**Comment by mxt305** [comment]
> Ok, I looked into this. I'm not happy with this solution because it involves more than just the variant property. It would be the ability to pass in any property to the TextInput within the renderInput of the Date* component.
> 
> This is unfortunately a much larger change than just this PR, so I'm going to close it. If you'd like to work on this with me, I'm happy to help you think about things further.

Because kybarg find the solution, this PR is unnecessary. 
I closed this PR on 14 March. However you opened it again.

**Comment by lookfirst** [comment]
Got it. Thanks!

**Pull request closed without merging**
