### PR TITLE
Fix adornments for `multiple` Autocomplete

### PR DESCRIPTION
**Pull request by jgabriele**
Fixes https://github.com/lookfirst/mui-rff/issues/469

### CODE REVIEW

**Comment by lookfirst** [comment]
This looks fantastic! Can you also include the test output snapshot? This will make your testing a bit easier as you won't have to test for specific things... just ensure the snapshot is the same. =) Up to you if you want to leave the existing expectations, but I'd also like the snapshot for completeness.

**Comment by jgabriele** [comment]
Sure :). I'm not a super fan of snapshots as I usually find it hard to maintain and to find what's wrong in the test. That's why I kept the initial implementation and added the snapshot in the end. Hope it's ok for you.

Let me know if you need anything else.

**Comment by lookfirst** [comment]
I like snaps because they capture things I may have missed in an expectation and I like that I can update all the dependencies of this project without even thinking and just know it'll work exactly the same (or at least throw errors if it doesn't!).

**Comment by lookfirst** [comment]
3.0.8 is released now. Thanks!

**Pull request merged**
