### PR TITLE
fix(helperText): default "helperText" not visible

### PR DESCRIPTION
**Pull request by keiches**
* TextField assign default "helperText", then it displays, but it always displays default helperText, when error occurring.
* DatePicker, KeyboardDatePicker, TimePicker assign default "helperText", but they never display, but when error occurring, error displays.

### CODE REVIEW

**Comment by lookfirst** [comment]
@keiches Thanks for the contribution, looks fantastic. Just checking if you've signed the CLA and I'll merge it. Probably not your fault, I bet you have... but the CLA site takes some time to update for some reason...

**Comment by lookfirst** [comment]
@keiches Seems like the CLA isn't signed. I'd love to get this into a release, so if you can sign it, that would be great. Otherwise, I'm going to have to reject the PR and hand apply things myself.

**Comment by keiches** [comment]
> @keiches Thanks for the contribution, looks fantastic. Just checking if you've signed the CLA and I'll merge it. Probably not your fault, I bet you have... but the CLA site takes some time to update for some reason...

Sorry I'm late. I signed the CLA. Thank you.

**Comment by lookfirst** [comment]
@keiches No worries, I just hand copied the changes. Thanks for signing it anyway. =)

**Comment by sajadghawami** [comment]
This also needs to be added for the Autocomplete!

**Pull request closed without merging**
