### PR TITLE
added switches (#83)

### PR DESCRIPTION
**Pull request by eterna2**
I need to use the switches. Looks better than checkbox when u just need a binary.

### CODE REVIEW

**Comment by eterna2** [comment]
Can u ping me when u release a new version? So that I can switch over.

**Comment by lookfirst** [comment]
Fantastic!

**Comment by lookfirst** [comment]
@eterna2 published as 1.9.0. Thanks again!

**Comment by lookfirst** [comment]
@eterna2 Interesting... I just played with the [example app](https://lookfirst.github.io/mui-rff/) and it is increasing the render count every time on the single switch.  i wonder what is up?

**Comment by lookfirst** [comment]
wild, but only if i click that one. as soon as i click another thing, it stops!

**Comment by eterna2** [comment]
Strange. Might need to look closer.
My code essentially is a replica of your checkboxes. 

Probably we shld try with a single checkbox too.

**Comment by lookfirst** [comment]
Yea, I know you did a great job.

Oh yea! there is a single checkbox on the page and it has the same issue!

you click it on/off and render count goes up.
you click on something else on the page.
click it again and no more render count issues.

hmmm... will have to play with this....

**Pull request merged**
