### PR TITLE
chore: upgrade to x-date-pickers v7

### PR DESCRIPTION
**Pull request by yann-combarnous**
This PR upgrades x-date-pickers to v7 @lookfirst.

### CODE REVIEW

**Comment by jon-hotaisle** [comment]
@yann-combarnous Thanks for the contribution! 

Couple points:

Please sign the CLA.

Please revert the version number change in package.json

What do you mean by the value parameter?

**Comment by lookfirst** [comment]
@yann-combarnous Thanks for the contribution!

Couple points:

Please sign the CLA.

Please revert the version number change in package.json

What do you mean by the value parameter?

**Comment by yann-combarnous** [comment]
> Please sign the CLA.

done

> Please revert the version number change in package.json

done

> What do you mean by the value parameter?

never mind, found the issue, fixed it @lookfirst

**Comment by yann-combarnous** [comment]
@lookfirst , ready for review.

Changes:

- bumped mui library versions to minimum for x-date-picker v7 requirements
- bumped typescript to latest patch version
- fixed typescript issues
- updated test snapshots, only class names changed

**Comment by lookfirst** [comment]
Thanks @yann-combarnous

**Pull request merged**
