### PR TITLE
Issue 186 validation types

### PR DESCRIPTION
**Pull request by alexjsdev**
Here's my quick solution to give two "validation type" options, I want to work on a solution to pass an override function for the showError function, but this is a stop gap to getting there. 

I've tested this locally it works great for what I (and sounds like others) need. Let me know if i missed anything. Thanks!

### CODE REVIEW

**Comment by lookfirst** [comment]
Thanks! This is good and a simple change, but I think I'd do it a bit more complete. People really want access to the whole function. I'd expose the ability to override the function and then possibly layer your change on top of that to choose from the two default implementations. Please correct me if I missed something, kind of late and eyes tired.

**Comment by alexjsdev** [comment]
@lookfirst that makes sense to me, like i said this was a "quick solution/ stop gap" I'll try to do the more complete version just pretty new to TS and not sure about how to fix any test i break. but i'll do what i can and put up a new PR soon. Thanks for the feedback.

**Comment by lookfirst** [comment]
@alexjsdev I'm going to leave this open for now. If you wouldn't mind signing the CLA, I might end up taking bits of it and I want to give you credit.

**Comment by alexjsdev** [comment]
@lookfirst signed. thanks! 

I'll prob get to working on the new PR next week, when I finally get back to the ticket i have related to integrating MUI components in my app at work. If you plan on doing a related release soon please let me know, thanks!

**Comment by lookfirst** [comment]
Thanks @alexjsdev ... I have some changes in flight that I want to make... it is almost done, but one test is failing and I haven't had time to focus on it yet... probably next week as well.

**Comment by alexjsdev** [comment]
@lookfirst I addressed this in new pr #235, it's ready to merge unless you have other suggestions or change requests. Lmk.

**Comment by lookfirst** [comment]
closing this as it was released in the other pr as version 2.3.0!

thanks again and apologies for the delays!

**Pull request closed without merging**
